theme: jekyll-theme-cayman
title: 2KD Engineering
description: Certificates of Compliance, Property Buliding Inspections, Snag Lists, Project Management, Surveying, Monitoring and Site Engineering Services, Design Work (Insulated Raft Foundation, ICF Masonry, Traditional Build).
github:
  is_project_page: false
